// public/frontend/libs/swiper/solid/get-children.js
import {children} from 'solid-js';

function childrenAsArray(c) {
    const cachedChildren = children(() => c);
    return Array.isArray(cachedChildren()) ? cachedChildren() : [cachedChildren()];
}

function processChildren(c) {
    const slides = [];
    childrenAsArray(c).forEach(child => {
        if (!child) return;

        if (child.className && child.className.indexOf('swiper-slide') >= 0) {
            slides.push(child);
        } else if (child.children) {
            processChildren(child.children).forEach(slide => slides.push(slide));
        }
    });
    return slides;
}

function getChildren(c) {
    const slides = [];
    const slots = {
        'container-start': [],
        'container-end': [],
        'wrapper-start': [],
        'wrapper-end': []
    };
    childrenAsArray(c).forEach(child => {
        if (!child) return;

        if (child.className && child.className.indexOf('swiper-slide') >= 0) {
            slides.push(child);
        } else if (child.slot && slots[child.slot]) {
            slots[child.slot].push(child);
        } else if (child.children) {
            const foundSlides = processChildren(child.children);

            if (foundSlides.length > 0) {
                foundSlides.forEach(slide => slides.push(slide));
            } else {
                slots['container-end'].push(child);
            }
        } else {
            slots['container-end'].push(child);
        }
    });
    return {
        slides,
        slots
    };
}

export {getChildren};

// public/frontend/libs/swiper/react/get-children.js
import React from 'react';

function isChildSwiperSlide(child) {
    return child.type && child.type.displayName && child.type.displayName.includes('SwiperSlide');
}

function processChildren(c) {
    const slides = [];
    React.Children.toArray(c).forEach(child => {
        if (isChildSwiperSlide(child)) {
            slides.push(child);
        } else if (child.props && child.props.children) {
            processChildren(child.props.children).forEach(slide => slides.push(slide));
        }
    });
    return slides;
}

function getChildren(c) {
    const slides = [];
    const slots = {
        'container-start': [],
        'container-end': [],
        'wrapper-start': [],
        'wrapper-end': []
    };
    React.Children.toArray(c).forEach(child => {
        if (isChildSwiperSlide(child)) {
            slides.push(child);
        } else if (child.props && child.props.slot && slots[child.props.slot]) {
            slots[child.props.slot].push(child);
        } else if (child.props && child.props.children) {
            const foundSlides = processChildren(child.props.children);

            if (foundSlides.length > 0) {
                foundSlides.forEach(slide => slides.push(slide));
            } else {
                slots['container-end'].push(child);
            }
        } else {
            slots['container-end'].push(child);
        }
    });
    return {
        slides,
        slots
    };
}

export {getChildren};
