// public/frontend/libs/swiper/react/swiper-slide.js
function _extends() {
    _extends = Object.assign ? Object.assign.bind() : function (target) {
        for (var i = 1; i < arguments.length; i++) {
            var source = arguments[i];
            for (var key in source) {
                if (Object.prototype.hasOwnProperty.call(source, key)) {
                    target[key] = source[key];
                }
            }
        }
        return target;
    };
    return _extends.apply(this, arguments);
}

import React, {useRef, useState, forwardRef} from 'react';
import {uniqueClasses} from '../components-shared/utils.js';
import {useIsomorphicLayoutEffect} from './use-isomorphic-layout-effect.js';
import {SwiperSlideContext} from './context.js';

const SwiperSlide = /*#__PURE__*/forwardRef(function (_temp, externalRef) {
    let {
        tag: Tag = 'div',
        children,
        className = '',
        swiper,
        zoom,
        virtualIndex,
        ...rest
    } = _temp === void 0 ? {} : _temp;
    const slideElRef = useRef(null);
    const [slideClasses, setSlideClasses] = useState('swiper-slide');

    function updateClasses(_s, el, classNames) {
        if (el === slideElRef.current) {
            setSlideClasses(classNames);
        }
    }

    useIsomorphicLayoutEffect(() => {
        if (externalRef) {
            externalRef.current = slideElRef.current;
        }

        if (!slideElRef.current || !swiper) {
            return;
        }

        if (swiper.destroyed) {
            if (slideClasses !== 'swiper-slide') {
                setSlideClasses('swiper-slide');
            }

            return;
        }

        swiper.on('_slideClass', updateClasses); // eslint-disable-next-line

        return () => {
            if (!swiper) return;
            swiper.off('_slideClass', updateClasses);
        };
    });
    useIsomorphicLayoutEffect(() => {
        if (swiper && slideElRef.current && !swiper.destroyed) {
            setSlideClasses(swiper.getSlideClasses(slideElRef.current));
        }
    }, [swiper]);
    const slideData = {
        isActive: slideClasses.indexOf('swiper-slide-active') >= 0 || slideClasses.indexOf('swiper-slide-duplicate-active') >= 0,
        isVisible: slideClasses.indexOf('swiper-slide-visible') >= 0,
        isDuplicate: slideClasses.indexOf('swiper-slide-duplicate') >= 0,
        isPrev: slideClasses.indexOf('swiper-slide-prev') >= 0 || slideClasses.indexOf('swiper-slide-duplicate-prev') >= 0,
        isNext: slideClasses.indexOf('swiper-slide-next') >= 0 || slideClasses.indexOf('swiper-slide-duplicate-next') >= 0
    };

    const renderChildren = () => {
        return typeof children === 'function' ? children(slideData) : children;
    };

    return /*#__PURE__*/React.createElement(Tag, _extends({
        ref: slideElRef,
        className: uniqueClasses(`${slideClasses}${className ? ` ${className}` : ''}`),
        "data-swiper-slide-index": virtualIndex
    }, rest), /*#__PURE__*/React.createElement(SwiperSlideContext.Provider, {
        value: slideData
    }, zoom ? /*#__PURE__*/React.createElement("div", {
        className: "swiper-zoom-container",
        "data-swiper-zoom": typeof zoom === 'number' ? zoom : undefined
    }, renderChildren()) : renderChildren()));
});
SwiperSlide.displayName = 'SwiperSlide';
export {SwiperSlide};

// public/frontend/libs/swiper/solid/swiper-slide.jsx
import {createEffect, createSignal, onCleanup, splitProps} from 'solid-js';
import {Dynamic} from 'solid-js/web';
import {SwiperSlideContext} from './context.js';
import {uniqueClasses} from '../components-shared/utils.js';

const SwiperSlide = (props) => {
    const [local, rest] = splitProps(props, [
        'children',
        'class',
        'ref',
        'swiper',
        'tag',
        'virtualIndex',
        'zoom',
    ]);

    const [slideClasses, setSlideClasses] = createSignal('swiper-slide');

    let ref = null;

    function updateClasses(_s, el, classNames) {
        if (el === ref) {
            setSlideClasses(classNames);
        }
    }

    createEffect(() => {
        if (!ref || !local.swiper) {
            return;
        }
        if (local.swiper.destroyed) {
            if (slideClasses() !== 'swiper-slide') {
                setSlideClasses('swiper-slide');
            }
            return;
        }
        local.swiper.on('_slideClass', updateClasses);
        // eslint-disable-next-line
        onCleanup(() => {
            if (!local.swiper) return;
            local.swiper.off('_slideClass', updateClasses);
        });
    });
    createEffect(() => {
        if (local.swiper && ref && !local.swiper.destroyed) {
            setSlideClasses(local.swiper.getSlideClasses(ref));
        }
    });

    const slideData = () => ({
        isActive:
            slideClasses().indexOf('swiper-slide-active') >= 0 ||
            slideClasses().indexOf('swiper-slide-duplicate-active') >= 0,
        isVisible: slideClasses().indexOf('swiper-slide-visible') >= 0,
        isDuplicate: slideClasses().indexOf('swiper-slide-duplicate') >= 0,
        isPrev:
            slideClasses().indexOf('swiper-slide-prev') >= 0 ||
            slideClasses().indexOf('swiper-slide-duplicate-prev') >= 0,
        isNext:
            slideClasses().indexOf('swiper-slide-next') >= 0 ||
            slideClasses().indexOf('swiper-slide-duplicate-next') >= 0,
    });

    const renderChildren = () => {
        return typeof local.children === 'function' ? local.children(slideData()) : local.children;
    };

    /* eslint-disable react/react-in-jsx-scope */
    /* eslint-disable react/no-unknown-property */

    return (
        <Dynamic
            component={local.tag || 'div'}
            ref={(el) => {
                ref = el;
                if (typeof local.ref === 'function') {
                    local.ref(el);
                } else {
                    local.ref = el;
                }
            }}
            class={uniqueClasses(`${slideClasses()}${local.class ? ` ${local.class}` : ''}`)}
            data-swiper-slide-index={local.virtualIndex}
            {...rest}
        >
            <SwiperSlideContext.Provider value={slideData()}>
                {local.zoom ? (
                    <div
                        class="swiper-zoom-container"
                        data-swiper-zoom={typeof local.zoom === 'number' ? local.zoom : undefined}
                    >
                        {renderChildren()}
                    </div>
                ) : (
                    renderChildren()
                )}
            </SwiperSlideContext.Provider>
        </Dynamic>
    );
};

export {SwiperSlide};
